Nmtlesson04/Models/Book.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Nmtlesson04.Models
{
    public class NmtBooks : Controller
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int AuthorId { get; set; }
        public int GenreId { get; set; }
        public string Image { get; set; }
        public float price { get; set; }
        public int TotaPage { get; set; }
        public string Summary { get; set; }

        public List<NmtBooks> GetBookList()
        {
            List<NmtBooks> books = new List<NmtBooks>()
            {
                new NmtBooks()
                {
                    Title = "ApspNe",
                    AuthorId = 1,
                    GenreId = 1,
                    Image = "/image/book01.jpg",
                    price = 12000,
                    TotaPage = 100,
                    Summary = ""
                },
                new NmtBooks()
                {
                    Title = "ApspNe",
                    AuthorId = 2,
                    GenreId = 2,
                    Image = "/image/book01.jpg",
                    price = 12000,
                    TotaPage = 100,
                    Summary = ""
                },
                new NmtBooks()
                {
                    Title = "ApspNe",
                    AuthorId = 3,
                    GenreId = 3,
                    Image = "/image/book03.jpg",
                    price = 12000,
                    TotaPage = 100,
                    Summary = ""
                },
            };
            return books;
        }

        public NmtBooks GetBookById(int id)
        {
            NmtBooks book = this.GetBookList().FirstOrDefault(b => b.Id == id);
            return book;
        }

        public List<SelectListItem> Authors { get; } = new List<SelectListItem>
        {
            new SelectListItem{ Value = "1", Text = "Nam Cao" },
            new SelectListItem{ Value = "2", Text = "Ngo Tat To" },
            new SelectListItem{ Value = "3", Text = "Adam Khoom" },
        };

        public List<SelectListItem> Genres { get; } = new List<SelectListItem>
        {
            new SelectListItem{ Value = "1", Text = "Truyen tranh" },
            new SelectListItem{ Value = "2", Text = "Van hoc duong dai" },
            new SelectListItem{ Value = "3", Text = "Phat hoc pho thong" },
        };
    }
}

Nmtlesson04/Models/ErrorViewModel.cs
namespace Nmtlesson04.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Nmtlesson04/Controllers/NmtBookController.cs
using Microsoft.AspNetCore.Mvc;
using Nmtlesson04.Models;

namespace Nmtlesson04.Controllers
{
    public class NmtBookController : Controller
    {
        protected NmtBooks book = new NmtBooks();

        public IActionResult NmtIndex()
        {
            ViewBag.authors = book.Authors;
            ViewBag.genres = book.Genres;
            var books = book.GetBookList();
            return View(books);
        }
    }
}

Nmtlesson04/Controllers/NmtHomeController.cs
using Microsoft.AspNetCore.Mvc;
using Nmtlesson04.Models;
using System.Diagnostics;

namespace Nmtlesson04.Controllers
{
    public class NmtHomeController : Controller
    {
        private readonly ILogger<NmtHomeController> _logger;

        public NmtHomeController(ILogger<NmtHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult NmtIndex()
        {
            return View();
        }

        public IActionResult NmtAbout()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Nmtlesson04/Views/NmtBook.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Nmtlesson04/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nmtlesson04</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Nmtlesson04.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @Html.Partial("_header")
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        @Html.Partial("_footer")
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Nmtlesson04/Views/Shared/_footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - Nmtlesson04 -
        <a asp-area="" asp-controller="NmtHome" asp-action="NmtAbuot">
            Thong tin sinh vien
        </a>
    </div>
</footer>

Nmtlesson04/Views/Shared/_header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="NmtBook" asp-action="NmtIndex">Nmtlesson04 - Nong Van Hung</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="NmtHome" asp-action="NmtIndex">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="NmtHome" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="NmtHome" asp-action="NmtAbout">Thong tin sinh vien</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="NmtBook" asp-action="NmtIndex">Book</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>