NmtLesson05Model/Models/DataModels/NmtMember.cs
namespace NmtLesson05Model.Models.DataModels
{
    public class NmtMember
    {
        public string NmtMemberID { get; set; }
        public string NmtUserName { get; set; }
        public string NmtFullName { get; set; }
        public string NmtPassword { get; set; }
        public string NmtEmail { get; set; }
    }
}

NmtLesson05Model/Models/ErrorViewModel.cs
namespace NmtLesson05Model.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NmtLesson05Model/Controllers/NmtHomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using NmtLesson05Model.Models;

namespace NmtLesson05Model.Controllers
{
    public class NmtHomeController : Controller
    {
        private readonly ILogger<NmtHomeController> _logger;

        public NmtHomeController(ILogger<NmtHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult NmtIndex()
        {
            return View();
        }

        public IActionResult NmtAbout()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NmtLesson05Model/Controllers/NmtMemberController.cs
using Microsoft.AspNetCore.Mvc;
using NmtLesson05Model.Models.DataModels;

namespace NmtLesson05Model.Controllers
{
    public class NmtMemberController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult NmtGetMember()
        {
            var nmtMember = new NmtMember();
            nmtMember.NmtMemberID = Guid.NewGuid().ToString();
            nmtMember.NmtUserName = "AniKmizu2262";
            nmtMember.NmtFullName = "Nguyễn Mạnh Tuấn";
            nmtMember.NmtPassword = "pass123";
            nmtMember.NmtEmail = "nguyenmanhtuantuan58@gmail.com";

            ViewBag.nmtMember = nmtMember;
            return View();
        }

    }
}

NmtLesson05Model/Views/NmtHome/NmtAbout.cshtml
@{
    ViewData["Title"] = "Thông tin SV";
}

<div class="alert alert-info">
    <h1>Thông tin SV</h1>
    <hr />
    <p>MSV : 2310900110</p>
    <p>Name : Nguyễn Mạnh Tuấn </p>
    <p>Class : K23CNT2</p>
    <p>Email : nguyenmanhtuantuan58@gmail.com</p>
    <p>Phone : 0123456789</p>
</div>

NmtLesson05Model/Views/NmtHome/NmtIndex.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NmtLesson05Model/Views/NmtMember/NmtGetMember.cshtml
@{
    ViewData["Title"] = "Member Info";
    var nmtMember = ViewBag.nmtMember as NmtLesson05Model.Models.DataModels.NmtMember;
}

<div class="alert alert-danger">
    <h1>Member Info</h1>
    <hr />
    <p>Member ID : @nmtMember.NmtMemberID</p>
    <p>Username : @nmtMember.NmtUserName </p>
    <p>FullName : @nmtMember.NmtFullName</p>
    <p>Password : @nmtMember.NmtPassword</p>
    <p>Email : @nmtMember.NmtEmail</p>
</div>

NmtLesson05Model/Views/Shared/_NmtLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NmtLesson05Model</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NmtLesson05Model.styles.css" asp-append-version="true" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="NmtIndex">NmtLesson05Model</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NmtHome" asp-action="NmtIndex">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NmtHome" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NmtHome" asp-action="NmtAbout">Thông tin sinh viên</a>
                        </li
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NmtMember" asp-action="NmtGetMember"> NmtGetMember</a>
                        </li
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - NmtLesson05Model - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>